spring:
  application:
    name: springconfigmapdemo
  cloud:
    kubernetes:
      config:
        enabled: false
      reload:
        enabled: false
        monitoring-config-maps: false
welcome:
  message: Welcome to learn about Spring Kubernetes ConfigMap 
  source: local (yaml file)
management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"